DELETE /paf/v1/ids-prefs?paf=eyJzZW5kZXIiOiJjbXAuY29tIiwicmVjZWl2ZXIiOiJvcGVyYXRvci5wYWYtb3BlcmF0aW9uLWRvbWFpbi5pbyIsInRpbWVzdGFtcCI6MTY0MzA0MTE0MCwic2lnbmF0dXJlIjoiaEt6OS94K3NpOTdyTlZCWGRrWHFDdUtzZko4ZmIxQkdFV1RxSHh5RFVDU2hORTgvemZiTEpTT0pyVXBOY3Z6Q1VxOG56Yjl4WFRva2ErRWN4WGxXamc9PSJ9
Host: operator.paf-operation-domain.io