DELETE /paf/v1/ids-prefs?paf=eyJzZW5kZXIiOiJjbXAuY29tIiwicmVjZWl2ZXIiOiJvcGVyYXRvci5wYWYtb3BlcmF0aW9uLWRvbWFpbi5pbyIsInRpbWVzdGFtcCI6MTY0MzA0MTE0MCwic2lnbmF0dXJlIjoiTUVVQ0lEWGJXMnlWOURPeUVvUzhSbmdoSWl2K1o4enZ6c2JHcm1FdmhRa21hVnRNQWlFQS9jQlFOS0lnTFk1QmRZSGhkbmQrdm15bnk0bTFjVXB0Vmd4Ulc2dmw3T2s9In0%3D
Host: operator.paf-operation-domain.io