GET /v1/ids-prefs?paf=eyJzZW5kZXIiOiJjbXAuY29tIiwicmVjZWl2ZXIiOiJvcGVyYXRvci5wYWYtb3BlcmF0aW9uLWRvbWFpbi5pbyIsInRpbWVzdGFtcCI6MTY0MzA0MTE0MCwic2lnbmF0dXJlIjoiWWRRS3I2VEloVUYra0RHdFd6cEYwQVRGaVU5Y1VHb1NhQk9JR0cyUFJ4UTQxU1R2U0pRUFFPb3FVYjFhN0dKVkVpaEdxUVhoZUlnaHVBQWVmU2tVakE9PSJ9
Host: operator.paf-operation-domain.io