GET /paf/v1/new-id?paf=eyJzZW5kZXIiOiJjbXAuY29tIiwicmVjZWl2ZXIiOiJvcGVyYXRvci5wYWYtb3BlcmF0aW9uLWRvbWFpbi5pbyIsInRpbWVzdGFtcCI6MTY0NjE1Nzg0MCwic2lnbmF0dXJlIjoiUHl0a1hIeFpqaHZqb3VyRFZpK3FaZURtR1QwWlU1S0ptRWF5RkpQbmFPWGFYSWx4Ti92NWhvVUgvdExKMHhEdlAzUk93dUswZDJwME54SmlyNGcrYmc9PSJ9
Host: operator.paf-operation-domain.io