GET /paf/v1/new-id?paf=eyJzZW5kZXIiOiJjbXAuY29tIiwicmVjZWl2ZXIiOiJvcGVyYXRvci5wYWYtb3BlcmF0aW9uLWRvbWFpbi5pbyIsInRpbWVzdGFtcCI6MTY0NjE1Nzg0MCwic2lnbmF0dXJlIjoiU2FDeGdZa2hFaDlBRUZ1TXVSWHg4cm9sU1d4K01Fc2VQZWtRUit2elduZXZBOWJaZ3FrN3JiL3lYcGp5OGgvKytqY1IvUndaenk0MDBzZWdUY1E3TWc9PSJ9
Host: operator.paf-operation-domain.io