GET /paf/v1/redirect/get-ids-prefs?paf=eyJyZXR1cm5VcmwiOiJodHRwczovL2FkdmVydGlzZXIuY29tL25ld3MvMjAyMi8wMi8wNy9zb21ldGhpbmctY3JhenktaGFwcGVuZWQ%2FdXRtX2NvbnRlbnQ9Y2FtcGFpZ24lMjBjb250ZW50IiwicmVxdWVzdCI6eyJzZW5kZXIiOiJjbXAuY29tIiwicmVjZWl2ZXIiOiJvcGVyYXRvci5wYWYtb3BlcmF0aW9uLWRvbWFpbi5pbyIsInRpbWVzdGFtcCI6MTY0MzA0MTE0MCwic2lnbmF0dXJlIjoidWJBSlRhUVltczVvTkRJbXpBQkRQTkxnR2E0VVh5clE2UFJZVElWQS96K1I2MmZ4U0Z3NEdlaGs4UmkxdVRNK0ZLWGxCKytWcXExL2RKdmpSYlNoNkE9PSJ9fQ%3D%3D
Host: operator.paf-operation-domain.io